version: '3.9'
services:
  backend:
    image: node:16-alpine
    container_name: ebitr_backend
    platform: linux/x86_64
    restart: 'always'
    ports:
      - 3001:3001 # localmente a porta 3001 do backend será acessada pelo navegador
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      # Os dados abaixo se referem ao container `db`
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=db
      - DB_NAME=ebitr_db
      - MYSQL_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
  db:
    image: mysql:8.0.21
    platform: linux/x86_64 
    container_name: db
    ports:
      - 3003:3306 # localmente o container db(MySQL) está escutando na porta 3003
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
